import type { ImageMetadata } from "astro";

const images = import.meta.glob<{ default: ImageMetadata }>("../assets/stack/*.{svg,png,jpg,jpeg}", { eager: true });

export const stackEnum: Record<string, number> = {
    SVG: 0,
    Description: 1,
    Category: 2,
} as const;

export const stackArray: Record<string, [ImageMetadata, string, string]> = {
    "C#": [images["../assets/stack/csharp-original.svg"].default, "Programming Language used for game development, web development, and more.", "Languages"],
    "C++": [images["../assets/stack/cplusplus-original.svg"].default, "Low-level programming language used for performance-critical applications, game development, and system programming.", "Languages"],
    CUDA: [images["../assets/stack/cuda-original.svg"].default, "Parallel computing platform and programming model developed by NVIDIA for GPU programming.", "Systems & Engines"],
    "MS SQL": [images["../assets/stack/microsoftsqlserver-original.svg"].default, "Relational database management system developed by Microsoft, used for storing and managing data in various applications.", "Databases"],
    "MS SQL Server": [images["../assets/stack/microsoftsqlserver-original.svg"].default, "Relational database management system developed by Microsoft, used for storing and managing data in various applications.", "Databases"],
    React: [images["../assets/stack/react-original.svg"].default, "JavaScript library for building user interfaces.", "Frontend & Styling"],
    "Node.js": [images["../assets/stack/nodejs-original.svg"].default, "JavaScript runtime built on Chrome's V8 JavaScript engine.", "Backend & Frameworks"],
    MongoDB: [images["../assets/stack/mongodb-original.svg"].default, "Document-oriented database management system.", "Databases"],
    TypeScript: [images["../assets/stack/typescript-original.svg"].default, "Typed superset of JavaScript that compiles to plain JavaScript.", "Languages"],
    "Three.js": [images["../assets/stack/threejs-original.svg"].default, "JavaScript 3D library for creating and displaying animated 3D computer graphics in a web browser.", "Frontend & Styling"],
    TailwindCSS: [images["../assets/stack/tailwindcss-original.svg"].default, "Utility-first CSS framework for rapidly building custom user interfaces.", "Frontend & Styling"],
    "ASP.NET Core": [images["../assets/stack/dotnetcore-original.svg"].default, "Free and open-source web framework developed by Microsoft.", "Backend & Frameworks"],
    Astro: [images["../assets/stack/astro-original.svg"].default, "Static site generator for building fast, content-focused websites.", "Backend & Frameworks"],
    Python: [images["../assets/stack/python-original.svg"].default, "High-level programming language known for its simplicity and readability.", "Languages"],
    DirectX11: [images["../assets/stack/directx-original.svg"].default, "Collection of APIs for handling tasks related to multimedia, especially game programming and video.", "Systems & Engines"],
    "DirectX 11": [images["../assets/stack/directx-original.svg"].default, "Collection of APIs for handling tasks related to multimedia, especially game programming and video.", "Systems & Engines"],
    Firebase: [images["../assets/stack/firebase-original.svg"].default, "Cloud-based platform for building web and mobile applications.", "Cloud & DevOps"],
    "Google Cloud Run": [images["../assets/stack/googlecloud-original.svg"].default, "Fully managed containerized application platform by Google.", "Cloud & DevOps"],
    "Google Cloud": [images["../assets/stack/googlecloud-original.svg"].default, "Cloud computing platform by Google.", "Cloud & DevOps"],
    "Unreal Engine": [images["../assets/stack/unrealengine-original.svg"].default, "Powerful game engine for creating high-quality interactive content.", "Systems & Engines"],
    Pandas: [images["../assets/stack/pandas-original.svg"].default, "Data analysis and manipulation library for Python.", "Data Science & AI"],
    FastAPI: [images["../assets/stack/fastapi-original.svg"].default, "Modern, fast (high-performance) web framework for building APIs with Python.", "Backend & Frameworks"],
    "SciKit-Learn": [images["../assets/stack/scikitlearn-original.svg"].default, "Machine learning library for Python.", "Data Science & AI"],
    Express: [images["../assets/stack/express-original.svg"].default, "Fast, unopinionated, minimalist web framework for Node.js.", "Backend & Frameworks"],
    Flask: [images["../assets/stack/flask-original.svg"].default, "Lightweight web application framework for Python.", "Backend & Frameworks"],
    Swift: [images["../assets/stack/swift-original.svg"].default, "General-purpose programming language developed by Apple.", "Languages"],
    JavaScript: [images["../assets/stack/javascript-original.svg"].default, "Programming language primarily used for creating interactive web pages.", "Languages"],
    HTML5: [images["../assets/stack/html5-original.svg"].default, "Markup language for structuring and presenting content on the World Wide Web.", "Languages"],
    MySQL: [images["../assets/stack/mysql-original.svg"].default, "Open-source relational database management system.", "Databases"],
    SQLite: [images["../assets/stack/sqlite-original.svg"].default, "Lightweight, serverless database engine.", "Databases"],
    Docker: [images["../assets/stack/docker-plain.svg"].default, "Platform for developing, shipping, and running applications in containers.", "Cloud & DevOps"],
    AWS: [images["../assets/stack/amazonwebservices-original-wordmark.svg"].default, "Cloud computing platform by Amazon.", "Cloud & DevOps"],
    Figma: [images["../assets/stack/figma-original.svg"].default, "Collaborative interface design tool.", "Tools & Design"],
    Postman: [images["../assets/stack/postman-original.svg"].default, "API development and testing platform.", "Tools & Design"],
    Swagger: [images["../assets/stack/swagger-original.svg"].default, "Platform for designing, building, documenting, and consuming RESTful web services.", "Tools & Design"],
    NPM: [images["../assets/stack/npm-original.svg"].default, "Package manager for Node.js.", "Tools & Design"],
    GitHub: [images["../assets/stack/github-original.svg"].default, "Web-based hosting service for version control using Git.", "Version Control Systems"],
    Git: [images["../assets/stack/git-original.svg"].default, "Distributed version control system.", "Version Control Systems"],
    Bitbucket: [images["../assets/stack/bitbucket-original.svg"].default, "Web-based version control repository management tool.", "Version Control Systems"],
    SourceTree: [images["../assets/stack/sourcetree-original.svg"].default, "Git client for Windows and Mac.", "Version Control Systems"],
    "VS Code": [images["../assets/stack/vscode-original.svg"].default, "Source-code editor developed by Microsoft.", "Development Environments"],
    "Visual Studio": [images["../assets/stack/visualstudio-original.svg"].default, "Integrated development environment (IDE) developed by Microsoft.", "Development Environments"],
    Xcode: [images["../assets/stack/xcode-original.svg"].default, "Integrated development environment (IDE) for macOS.", "Development Environments"],
    Unity: [images["../assets/stack/unity-original.svg"].default, "Multi-platform game engine.", "Systems & Engines"],
    OpenGL: [images["../assets/stack/opengl-plain.svg"].default, "API for rendering 2D and 3D vector graphics.", "Systems & Engines"],
    Linux: [images["../assets/stack/linux-original.svg"].default, "Open-source operating system.", "Systems & Engines"],
    Ubuntu: [images["../assets/stack/ubuntu-original.svg"].default, "Popular Linux distribution.", "Systems & Engines"],
    Windows: [images["../assets/stack/windows11-original.svg"].default, "Operating system developed by Microsoft.", "Systems & Engines"],
    Arduino: [images["../assets/stack/arduino-original.svg"].default, "Open-source electronics platform.", "Systems & Engines"],
};