export const stackEnum: Record<string, number> = {
    SVG: 0,
    Description: 1,
} as const;

export const stackSVG: Record<string, [string, string]> = {
    "C#": ["/portfolio/stack/csharp-original.svg", "Programming Language used for game development, web development, and more."],
    "C++": ["/portfolio/stack/cplusplus-original.svg", "Low-level programming language used for performance-critical applications, game development, and system programming."],
    CUDA: ["/portfolio/stack/cuda-original.svg", "Parallel computing platform and programming model developed by NVIDIA for GPU programming."],
    "MS SQL": ["/portfolio/stack/microsoftsqlserver-original.svg", "Relational database management system developed by Microsoft, used for storing and managing data in various applications."],
    "MS SQL Server": ["/portfolio/stack/microsoftsqlserver-original.svg", "Relational database management system developed by Microsoft, used for storing and managing data in various applications."],
    React: ["/portfolio/stack/react-original.svg", "JavaScript library for building user interfaces."],
    "Node.js": ["/portfolio/stack/nodejs-original.svg", "JavaScript runtime built on Chrome's V8 JavaScript engine."],
    MongoDB: ["/portfolio/stack/mongodb-original.svg", "Document-oriented database management system."],
    TypeScript: ["/portfolio/stack/typescript-original.svg", "Typed superset of JavaScript that compiles to plain JavaScript."],
    "Three.js": ["/portfolio/stack/threejs-original.svg", "JavaScript 3D library for creating and displaying animated 3D computer graphics in a web browser."],
    TailwindCSS: ["/portfolio/stack/tailwindcss-original.svg", "Utility-first CSS framework for rapidly building custom user interfaces."],
    "ASP.NET Core": ["/portfolio/stack/dotnetcore-original.svg", "Free and open-source web framework developed by Microsoft."],
    Astro: ["/portfolio/stack/astro-original.svg", "Static site generator for building fast, content-focused websites."],
    Python: ["/portfolio/stack/python-original.svg", "High-level programming language known for its simplicity and readability."],
    DirectX11: ["/portfolio/stack/directx-original.svg", "Collection of APIs for handling tasks related to multimedia, especially game programming and video."],
    "DirectX 11": ["/portfolio/stack/directx-original.svg", "Collection of APIs for handling tasks related to multimedia, especially game programming and video."],
    Firebase: ["/portfolio/stack/firebase-original.svg", "Cloud-based platform for building web and mobile applications."],
    "Google Cloud Run": ["/portfolio/stack/googlecloud-original.svg", "Fully managed containerized application platform by Google."],
    "Google Cloud": ["/portfolio/stack/googlecloud-original.svg", "Cloud computing platform by Google."],
    "Unreal Engine": ["/portfolio/stack/unrealengine-original.svg", "Powerful game engine for creating high-quality interactive content."],
    Pandas: ["/portfolio/stack/pandas-original.svg", "Data analysis and manipulation library for Python."],
    FastAPI: ["/portfolio/stack/fastapi-original.svg", "Modern, fast (high-performance) web framework for building APIs with Python."],
    "SciKit-Learn": ["/portfolio/stack/scikitlearn-original.svg", "Machine learning library for Python."],
    Express: ["/portfolio/stack/express-original.svg", "Fast, unopinionated, minimalist web framework for Node.js."],
    Flask: ["/portfolio/stack/flask-original.svg", "Lightweight web application framework for Python."],
    Swift: ["/portfolio/stack/swift-original.svg", "General-purpose programming language developed by Apple."],
    JavaScript: ["/portfolio/stack/javascript-original.svg", "Programming language primarily used for creating interactive web pages."],
    HTML5: ["/portfolio/stack/html5-original.svg", "Markup language for structuring and presenting content on the World Wide Web."],
    MySQL: ["/portfolio/stack/mysql-original.svg", "Open-source relational database management system."],
    SQLite: ["/portfolio/stack/sqlite-original.svg", "Lightweight, serverless database engine."],
    Docker: ["/portfolio/stack/docker-plain.svg", "Platform for developing, shipping, and running applications in containers."],
    AWS: ["/portfolio/stack/amazonwebservices-original-wordmark.svg", "Cloud computing platform by Amazon."],
    Figma: ["/portfolio/stack/figma-original.svg", "Collaborative interface design tool."],
    Postman: ["/portfolio/stack/postman-original.svg", "API development and testing platform."],
    Swagger: ["/portfolio/stack/swagger-original.svg", "Platform for designing, building, documenting, and consuming RESTful web services."],
    NPM: ["/portfolio/stack/npm-original.svg", "Package manager for Node.js."],
    GitHub: ["/portfolio/stack/github-original.svg", "Web-based hosting service for version control using Git."],
    Git: ["/portfolio/stack/git-original.svg", "Distributed version control system."],
    Bitbucket: ["/portfolio/stack/bitbucket-original.svg", "Web-based version control repository management tool."],
    SourceTree: ["/portfolio/stack/sourcetree-original.svg", "Git client for Windows and Mac."],
    "VS Code": ["/portfolio/stack/vscode-original.svg", "Source-code editor developed by Microsoft."],
    "Visual Studio": ["/portfolio/stack/visualstudio-original.svg", "Integrated development environment (IDE) developed by Microsoft."],
    Xcode: ["/portfolio/stack/xcode-original.svg", "Integrated development environment (IDE) for macOS."],
    Unity: ["/portfolio/stack/unity-original.svg", "Multi-platform game engine."],
    OpenGL: ["/portfolio/stack/opengl-plain.svg", "API for rendering 2D and 3D vector graphics."],
    Linux: ["/portfolio/stack/linux-original.svg", "Open-source operating system."],
    Ubuntu: ["/portfolio/stack/ubuntu-original.svg", "Popular Linux distribution."],
    Windows: ["/portfolio/stack/windows11-original.svg", "Operating system developed by Microsoft."],
    Arduino: ["/portfolio/stack/arduino-original.svg", "Open-source electronics platform."],
};