import type { ImageMetadata } from "astro";

const images = import.meta.glob<{ default: ImageMetadata }>("../assets/stack/*.{svg,png,jpg,jpeg}", { eager: true });

export const stackEnum: Record<string, number> = {
    SVG: 0,
    Description: 1,
} as const;

export const stackSVG: Record<string, [ImageMetadata, string]> = {
    "C#": [images["../assets/stack/csharp-original.svg"].default, "Programming Language used for game development, web development, and more."],
    "C++": [images["../assets/stack/cplusplus-original.svg"].default, "Low-level programming language used for performance-critical applications, game development, and system programming."],
    CUDA: [images["../assets/stack/cuda-original.svg"].default, "Parallel computing platform and programming model developed by NVIDIA for GPU programming."],
    "MS SQL": [images["../assets/stack/microsoftsqlserver-original.svg"].default, "Relational database management system developed by Microsoft, used for storing and managing data in various applications."],
    "MS SQL Server": [images["../assets/stack/microsoftsqlserver-original.svg"].default, "Relational database management system developed by Microsoft, used for storing and managing data in various applications."],
    React: [images["../assets/stack/react-original.svg"].default, "JavaScript library for building user interfaces."],
    "Node.js": [images["../assets/stack/nodejs-original.svg"].default, "JavaScript runtime built on Chrome's V8 JavaScript engine."],
    MongoDB: [images["../assets/stack/mongodb-original.svg"].default, "Document-oriented database management system."],
    TypeScript: [images["../assets/stack/typescript-original.svg"].default, "Typed superset of JavaScript that compiles to plain JavaScript."],
    "Three.js": [images["../assets/stack/threejs-original.svg"].default, "JavaScript 3D library for creating and displaying animated 3D computer graphics in a web browser."],
    TailwindCSS: [images["../assets/stack/tailwindcss-original.svg"].default, "Utility-first CSS framework for rapidly building custom user interfaces."],
    "ASP.NET Core": [images["../assets/stack/dotnetcore-original.svg"].default, "Free and open-source web framework developed by Microsoft."],
    Astro: [images["../assets/stack/astro-original.svg"].default, "Static site generator for building fast, content-focused websites."],
    Python: [images["../assets/stack/python-original.svg"].default, "High-level programming language known for its simplicity and readability."],
    DirectX11: [images["../assets/stack/directx-original.svg"].default, "Collection of APIs for handling tasks related to multimedia, especially game programming and video."],
    "DirectX 11": [images["../assets/stack/directx-original.svg"].default, "Collection of APIs for handling tasks related to multimedia, especially game programming and video."],
    Firebase: [images["../assets/stack/firebase-original.svg"].default, "Cloud-based platform for building web and mobile applications."],
    "Google Cloud Run": [images["../assets/stack/googlecloud-original.svg"].default, "Fully managed containerized application platform by Google."],
    "Google Cloud": [images["../assets/stack/googlecloud-original.svg"].default, "Cloud computing platform by Google."],
    "Unreal Engine": [images["../assets/stack/unrealengine-original.svg"].default, "Powerful game engine for creating high-quality interactive content."],
    Pandas: [images["../assets/stack/pandas-original.svg"].default, "Data analysis and manipulation library for Python."],
    FastAPI: [images["../assets/stack/fastapi-original.svg"].default, "Modern, fast (high-performance) web framework for building APIs with Python."],
    "SciKit-Learn": [images["../assets/stack/scikitlearn-original.svg"].default, "Machine learning library for Python."],
    Express: [images["../assets/stack/express-original.svg"].default, "Fast, unopinionated, minimalist web framework for Node.js."],
    Flask: [images["../assets/stack/flask-original.svg"].default, "Lightweight web application framework for Python."],
    Swift: [images["../assets/stack/swift-original.svg"].default, "General-purpose programming language developed by Apple."],
    JavaScript: [images["../assets/stack/javascript-original.svg"].default, "Programming language primarily used for creating interactive web pages."],
    HTML5: [images["../assets/stack/html5-original.svg"].default, "Markup language for structuring and presenting content on the World Wide Web."],
    MySQL: [images["../assets/stack/mysql-original.svg"].default, "Open-source relational database management system."],
    SQLite: [images["../assets/stack/sqlite-original.svg"].default, "Lightweight, serverless database engine."],
    Docker: [images["../assets/stack/docker-plain.svg"].default, "Platform for developing, shipping, and running applications in containers."],
    AWS: [images["../assets/stack/amazonwebservices-original-wordmark.svg"].default, "Cloud computing platform by Amazon."],
    Figma: [images["../assets/stack/figma-original.svg"].default, "Collaborative interface design tool."],
    Postman: [images["../assets/stack/postman-original.svg"].default, "API development and testing platform."],
    Swagger: [images["../assets/stack/swagger-original.svg"].default, "Platform for designing, building, documenting, and consuming RESTful web services."],
    NPM: [images["../assets/stack/npm-original.svg"].default, "Package manager for Node.js."],
    GitHub: [images["../assets/stack/github-original.svg"].default, "Web-based hosting service for version control using Git."],
    Git: [images["../assets/stack/git-original.svg"].default, "Distributed version control system."],
    Bitbucket: [images["../assets/stack/bitbucket-original.svg"].default, "Web-based version control repository management tool."],
    SourceTree: [images["../assets/stack/sourcetree-original.svg"].default, "Git client for Windows and Mac."],
    "VS Code": [images["../assets/stack/vscode-original.svg"].default, "Source-code editor developed by Microsoft."],
    "Visual Studio": [images["../assets/stack/visualstudio-original.svg"].default, "Integrated development environment (IDE) developed by Microsoft."],
    Xcode: [images["../assets/stack/xcode-original.svg"].default, "Integrated development environment (IDE) for macOS."],
    Unity: [images["../assets/stack/unity-original.svg"].default, "Multi-platform game engine."],
    OpenGL: [images["../assets/stack/opengl-plain.svg"].default, "API for rendering 2D and 3D vector graphics."],
    Linux: [images["../assets/stack/linux-original.svg"].default, "Open-source operating system."],
    Ubuntu: [images["../assets/stack/ubuntu-original.svg"].default, "Popular Linux distribution."],
    Windows: [images["../assets/stack/windows11-original.svg"].default, "Operating system developed by Microsoft."],
    Arduino: [images["../assets/stack/arduino-original.svg"].default, "Open-source electronics platform."],
};