export const stackSVG: Record<string, string> = {
    "C#": "/portfolio/stack/csharp-original.svg",
    "C++": "/portfolio/stack/cplusplus-original.svg",
    CUDA: "/portfolio/stack/cuda-original.svg",
    "MS SQL": "/portfolio/stack/microsoftsqlserver-original.svg",
    "MS SQL Server": "/portfolio/stack/microsoftsqlserver-original.svg",
    React: "/portfolio/stack/react-original.svg",
    "Node.js": "/portfolio/stack/nodejs-original.svg",
    MongoDB: "/portfolio/stack/mongodb-original.svg",
    TypeScript: "/portfolio/stack/typescript-original.svg",
    "Three.js": "/portfolio/stack/threejs-original.svg",
    TailwindCSS: "/portfolio/stack/tailwindcss-original.svg",
    "ASP.NET Core": "/portfolio/stack/dotnetcore-original.svg",
    Astro: "/portfolio/stack/astro-original.svg",
    Python: "/portfolio/stack/python-original.svg",
    DirectX11: "/portfolio/stack/directx-original.svg",
    "DirectX 11": "/portfolio/stack/directx-original.svg",
    Firebase: "/portfolio/stack/firebase-original.svg",
    "Google Cloud Run": "/portfolio/stack/googlecloud-original.svg",
    "Google Cloud": "/portfolio/stack/googlecloud-original.svg",
    "Unreal Engine": "/portfolio/stack/unrealengine-original.svg",
    Pandas: "/portfolio/stack/pandas-original.svg",
    FastAPI: "/portfolio/stack/fastapi-original.svg",
    "SciKit-Learn": "/portfolio/stack/scikitlearn-original.svg",
    Express: "/portfolio/stack/express-original.svg",
    Flask: "/portfolio/stack/flask-original.svg",
    Swift: "/portfolio/stack/swift-original.svg",
    JavaScript: "/portfolio/stack/javascript-original.svg",
    HTML5: "/portfolio/stack/html5-original.svg",
    MySQL: "/portfolio/stack/mysql-original.svg",
    SQLite: "/portfolio/stack/sqlite-original.svg",
    Docker: "/portfolio/stack/docker-plain.svg",
    AWS: "/portfolio/stack/amazonwebservices-original-wordmark.svg",
    Figma: "/portfolio/stack/figma-original.svg",
    Postman: "/portfolio/stack/postman-original.svg",
    Swagger: "/portfolio/stack/swagger-original.svg",
    NPM: "/portfolio/stack/npm-original.svg",
    GitHub: "/portfolio/stack/github-original.svg",
    Git: "/portfolio/stack/git-original.svg",
    Bitbucket: "/portfolio/stack/bitbucket-original.svg",
    SourceTree: "/portfolio/stack/sourcetree-original.svg",
    "VS Code": "/portfolio/stack/vscode-original.svg",
    "Visual Studio": "/portfolio/stack/visualstudio-original.svg",
    Xcode: "/portfolio/stack/xcode-original.svg",
    Unity: "/portfolio/stack/unity-original.svg",
    OpenGL: "/portfolio/stack/opengl-plain.svg",
    Linux: "/portfolio/stack/linux-original.svg",
    Ubuntu: "/portfolio/stack/ubuntu-original.svg",
    Windows: "/portfolio/stack/windows11-original.svg",
    Arduino: "/portfolio/stack/arduino-original.svg",
};